name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mihails-strasuns/setup-dlang@v0.5.0
    - name: Check syntax
      run: dub lint --syntax-check
    - name: Check style
      run: dub lint --style-check
