name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup D environment
      run: curl https://dlang.org/install.sh -fsS | bash -c install ldc
