name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup D environment
      run: |
        mkdir ~/dlang
        curl https://dlang.org/install.sh -o ~/dlang/install.sh
        ~/dlang/install.sh install ldc
        ~/dlang/install.sh install dub
