name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup D environment
      run: curl https://dlang.org/install.sh | bash -s install ldc
    - name: Activate D environmant
      run: source ~/dlang/$(~/dlang/install.sh list)/activate
    - name: echo $PATH
      run: source ~/dlang/$(~/dlang/install.sh list)/activate && echo $PATH
    - name: Touch Dub
      run: dub --help
